export const dogSize = [
  { id: 1, name: '소형견' },
  { id: 2, name: '중형견' },
  { id: 3, name: '대형견' },
];

export const dogBreed = [
  { id: 1, name: '리트리버' },
  { id: 2, name: '닥스훈트' },
  { id: 3, name: '말티즈' },
  { id: 4, name: '페키니즈' },
  { id: 5, name: '푸들' },
  { id: 6, name: '슈나이저' },
  { id: 7, name: '보더콜리' },
  { id: 8, name: '비글' },
  { id: 9, name: '비숑' },
  { id: 10, name: '사모예드' },
  { id: 11, name: '보스턴 테리어' },
  { id: 12, name: '시츄' },
  { id: 13, name: '셰틀랜드 쉽독' },
  { id: 14, name: '시바견' },
  { id: 15, name: '시베리안 허스키' },
  { id: 16, name: '웰시 코기' },
  { id: 17, name: '진돗개' },
  { id: 18, name: '치와와' },
  { id: 19, name: '믹스견' },
  { id: 20, name: '요크셔 테리어' },
  { id: 21, name: '코커 스패니얼' },
  { id: 22, name: '이탈리안 그레이하운드' },
  { id: 23, name: '파피용' },
  { id: 24, name: '퍼그' },
  { id: 25, name: '포메라니안' },
  { id: 26, name: '풍산개' },
  { id: 27, name: '불독' },
  { id: 29, name: '미니어처 핀셔' },
  { id: 30, name: '기타' },
];
